/*
 * Copyright (C) 2019-2026 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package com.here.unittesting

import com.here.sdk.core.Angle
import com.here.sdk.core.GeoCoordinates
import com.here.sdk.core.GeoCoordinatesUpdate
import com.here.sdk.core.GeoOrientation
import com.here.sdk.mapview.MapCamera
import com.here.sdk.mapview.MapCameraAnimation
import com.here.sdk.mapview.MapCameraAnimationFactory
import com.here.sdk.mapview.MapView
import com.here.time.Duration
import junit.framework.TestCase.assertEquals
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.mockito.ArgumentMatchers.anyDouble
import org.mockito.Mockito.mock
import org.mockito.Mockito.times
import org.mockito.Mockito.verify
import org.mockito.Mockito.verifyNoMoreInteractions
import org.mockito.Mockito.`when`
import org.mockito.Mockito.withSettings
import org.mockito.junit.MockitoJUnitRunner

/**
 * The HERE SDK's Mocking library provides constructor helpers that assist in initializing
 * struct-like classes. These helpers automatically initialize public non-static fields whose
 * names match the constructor parameter names. When parameter and field names do not match,
 * a custom implementation can be provided.
 *
 * To provide a custom implementation, you must either:
 * - Implement the `ConstructorHelper` interface, or
 * - Extend the `ConstructorHelperImpl` class and set the `ConstructorMockHelperInstance` field
 *   to this implementation.
 *
 * The `ConstructorHelper` interface contains methods named `_constructor(...)`, with one method
 * for each constructor in the class where it is nested. Each `_constructor(...)` method has the same
 * parameters as the related constructor and returns an instance of the class.
 *
 * The `ConstructorHelperImpl` class implements the `ConstructorHelper` interface and provides default
 * implementations as described above. It is useful to extend this class and override only specific
 * `_constructor(...)` methods as needed. Each constructor, except the parameterless one, calls the
 * related version of `ConstructorMockHelperInstance._constructor(...)` and copies all public fields
 * from the returned instance to the current instance.
 *
 * Rule of thumb: When the constructor contains parameter names that are not exposed as members,
 * use the ConstructorMockHelperInstance approach. Otherwise, not.
 */
class GeoCoordinatesUpdateMockHelper :
    GeoCoordinatesUpdate.ConstructorHelperImpl() {

    /**
     * The `GeoCoordinatesUpdate` class does not have a `coordinates` field. Instead, it has
     * `latitude`, `longitude`, and `altitude` fields. As a result, the default implementation of
     * `GeoCoordinatesUpdate.ConstructorHelperImpl` cannot initialize these fields. Therefore,
     * it is necessary to initialize them using custom logic.
     */
    override fun _constructor(coordinates: GeoCoordinates): GeoCoordinatesUpdate {
        // Each class of the HERE SDK's Mock Library contains a parameterless constructor,
        // even if the original class doesn't.
        // This constructor can be used to create instances of the class and initialize
        // fields with default values.
        val result = GeoCoordinatesUpdate()

        result.latitude = coordinates.latitude
        result.longitude = coordinates.longitude
        result.altitude = coordinates.altitude

        // All public fields are copied in constructor
        // "GeoCoordinatesUpdate(@NonNull final GeoCoordinates coordinates)"
        return result
    }
}

@RunWith(MockitoJUnitRunner::class)
class TestBasicTypes {

    // These tests show examples of how the HERE SDK can be accessed in a unit test scenario.

    @Before
    fun setUp() {
        // Use custom logic for constructors of "GeoCoordinatesUpdate" class.
        GeoCoordinatesUpdate.ConstructorMockHelperInstance =
            GeoCoordinatesUpdateMockHelper()
    }

    @After
    fun tearDown() {
        // Reset back to default implementation.
        GeoCoordinatesUpdate.ConstructorMockHelperInstance =
            GeoCoordinatesUpdate.ConstructorHelperImpl()
    }

    @Test
    fun testAutoGeneratedConstructor() {
        // "GeoCoordinates" has a constructor with parameters "latitude" and "longitude" and
        // it has fields with the same names, so in the example below the mentioned fields are
        // initialized by the constructor's parameters and altitude has its default value.
        val geoCoordinates = GeoCoordinates(10.0, 20.0)

        assertEquals(geoCoordinates.latitude, 10.0)
        assertEquals(geoCoordinates.longitude, 20.0)
    }

    @Test
    fun testSelfImplementedConstructor() {
        val geoCoordinates = GeoCoordinates(5.0, 10.0, 20.0)

        // This constructor uses "GeoCoordinatesUpdateMockHelper", which is set in "setUp".
        val geoCoordinatesUpdate = GeoCoordinatesUpdate(geoCoordinates)

        assertEquals(geoCoordinatesUpdate.latitude, 5.0)
        assertEquals(geoCoordinatesUpdate.longitude, 10.0)
        assertEquals(geoCoordinatesUpdate.altitude, 20.0)
    }

    @Test
    fun testNonStaticMethod() {
        val angleMock = mock(Angle::class.java)

        `when`(angleMock.degrees).thenReturn(10.0)

        assertEquals(10.0, angleMock.degrees)

        verify(angleMock, times(1)).degrees
        verifyNoMoreInteractions(angleMock)
    }

    @Test
    fun testStaticMethod() {
        val angleMock = mock(Angle::class.java)
        `when`(angleMock.degrees).thenReturn(10.0)

        // Each HERE SDK class with static methods contains helper code to make mocking easier.
        // Add heresdk-xxx.jar to access these additional mock helper instances.
        Angle.StaticMockHelperInstance =
            mock(Angle.StaticMockHelper::class.java)

        `when`(
            Angle.StaticMockHelperInstance.fromRadians(anyDouble())
        ).thenReturn(angleMock)

        // Test static creation of Angle class.
        // Static HERE SDK classes require a StaticMockHelperInstance.
        assertEquals(
            10.0,
            Angle.fromRadians(0.174533).degrees
        )

        verify(
            Angle.StaticMockHelperInstance,
            times(1)
        ).fromRadians(anyDouble())

        verify(angleMock, times(1)).degrees

        verifyNoMoreInteractions(Angle.StaticMockHelperInstance)
        verifyNoMoreInteractions(angleMock)
    }

    @Test
    fun testMapView() {
        val targetCoordinates = mock(GeoCoordinates::class.java)
        val orientationAtTarget = mock(GeoOrientation::class.java)

        val distanceInMeters = 5000.0
        val zoomLevel = 1000.0

        val bowFactor = 1.0
        val duration = mock(Duration::class.java)
        val geoCoordinatesUpdate = mock(GeoCoordinatesUpdate::class.java)

        val mapView = mock(MapView::class.java)

        // When a mock is declared as lenient, none of its stubbings will be checked
        // for "unnecessary stubbing".
        val mapCamera = mock(
            MapCamera::class.java,
            withSettings().lenient()
        )

        val state = MapCamera.State(
            targetCoordinates,
            orientationAtTarget,
            distanceInMeters,
            zoomLevel
        )

        val mapCameraAnimation =
            mock(MapCameraAnimation::class.java)

        MapCameraAnimationFactory.StaticMockHelperInstance =
            mock(MapCameraAnimationFactory.StaticMockHelper::class.java)

        `when`(mapView.width).thenReturn(100)
        `when`(mapView.height).thenReturn(100)
        `when`(mapCamera.state).thenReturn(state)

        `when`(
            MapCameraAnimationFactory.StaticMockHelperInstance.flyTo(
                geoCoordinatesUpdate,
                bowFactor,
                duration
            )
        ).thenReturn(mapCameraAnimation)

        // This verifies that the HERE SDK's MapView can be mocked as expected.
        assertEquals(100, mapView.width)
        assertEquals(100, mapView.height)

        // This verifies that the HERE SDK's MapCamera can be mocked as expected.
        assertEquals(state, mapCamera.state)

        assertEquals(
            mapCameraAnimation,
            MapCameraAnimationFactory.StaticMockHelperInstance.flyTo(
                geoCoordinatesUpdate,
                bowFactor,
                duration
            )
        )

        verify(mapView, times(1)).width
        verify(mapView, times(1)).height
        verify(mapCamera, times(1)).state
    }
}
