apply plugin: 'com.android.application'

android {
    compileSdk 35
    defaultConfig {
        applicationId "com.here.traffic"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    namespace 'com.here.traffic'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'

    // For this example app, we use the latest release via "4.+" to always resolve the newest version from artifactory.
    // Alternatively, hardcode the version, e.g. def HERESDKVersion = "4.27.1.0", this is recommended for
    // production apps to keep your dependencies stable.
    // If you are using CI, the version could be passed explicitly via -PHERESDKVersion.
    def HERESDKVersion = project.hasProperty('HERESDKVersion') ? project.getProperty('HERESDKVersion') : "4.+"

    // Optional artifact suffix for internal releases to support different build flavors.
    // Should be empty, by default.
    def HERESDKSuffix = project.hasProperty('hereSDKSuffix') ? "-${hereSDKSuffix}" : ""

    // HERE SDK Units helpers (PermissionsRequestor etc.) are always loaded from libs.
    implementation fileTree(dir: 'libs', include: ['*.aar', '*.jar'], exclude: ['*mock*.jar', 'heresdk*.aar'])

    // The HERESDKBuildConfig is set in the root build.gradle file.
    if (HERESDKBuildConfig == "COMPONENTS_FROM_ARTIFACTORY") {
        implementation "com.here.here-sdk.java.components:here-sdk-map-advanced${HERESDKSuffix}:${HERESDKVersion}"
        implementation "com.here.here-sdk.java.components:here-sdk-routing-online${HERESDKSuffix}:${HERESDKVersion}"
        implementation "com.here.here-sdk.java.components:here-sdk-traffic${HERESDKSuffix}:${HERESDKVersion}"
    } else {
        // Default: LOCAL_BUNDLE - place the HERE SDK AAR manually in app/libs.
        implementation fileTree(dir: 'libs', include: ['heresdk*.aar'])
        // When using local .aar files (LOCAL_BUNDLE), there's no accompanying POM file to declare transitive dependencies
        // such as Kotlin standard library.
        implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.20"
    }
}
